<?php

namespace Database\Seeders\Core;

use App\Models\Core\Language;
use Illuminate\Database\Seeder;

class AdminLanguageSeeder extends Seeder
{
    /** @var list<string> */
    private const ACTIVE_LANGUAGE_CODES = ['en', 'ur','fr'];

    public function run(): void
    {
        foreach ($this->definitions() as $row) {
            Language::updateOrCreate(
                [
                    'code' => $row['code'],
                    'region_code' => $row['region_code'] ?? '',
                ],
                [
                    'name' => $row['name'],
                    'is_rtl' => $row['is_rtl'],
                    'sort_order' => $row['sort_order'],
                    'is_active' => $this->isActiveLanguage($row) || ($row['is_system'] ?? false),
                    'is_system' => $row['is_system'] ?? false,
                ]
            );
        }
    }

    private function isActiveLanguage(array $row): bool
    {
        $region = $row['region_code'] ?? '';

        return $region === ''
            && in_array($row['code'], self::ACTIVE_LANGUAGE_CODES, true);
    }

    /**
     * @return list<array{code: string, region_code?: string, name: string, sort_order: int, is_rtl: bool, system?: bool}>
     */
    private function definitions(): array
    {
        return [
            ['code' => 'ab', 'name' => 'Abkhazian', 'sort_order' => 10, 'is_rtl' => false],
            ['code' => 'aa', 'name' => 'Afar', 'sort_order' => 20, 'is_rtl' => false],
            ['code' => 'af', 'name' => 'Afrikaans', 'sort_order' => 30, 'is_rtl' => false],
            ['code' => 'ak', 'name' => 'Akan', 'sort_order' => 40, 'is_rtl' => false],
            ['code' => 'sq', 'name' => 'Albanian', 'sort_order' => 50, 'is_rtl' => false],
            ['code' => 'am', 'name' => 'Amharic', 'sort_order' => 60, 'is_rtl' => false],
            ['code' => 'ar', 'name' => 'Arabic', 'sort_order' => 70, 'is_rtl' => true],
            ['code' => 'an', 'name' => 'Aragonese', 'sort_order' => 80, 'is_rtl' => false],
            ['code' => 'hy', 'name' => 'Armenian', 'sort_order' => 90, 'is_rtl' => false],
            ['code' => 'as', 'name' => 'Assamese', 'sort_order' => 100, 'is_rtl' => false],
            ['code' => 'av', 'name' => 'Avaric', 'sort_order' => 110, 'is_rtl' => false],
            ['code' => 'ae', 'name' => 'Avestan', 'sort_order' => 120, 'is_rtl' => false],
            ['code' => 'ay', 'name' => 'Aymara', 'sort_order' => 130, 'is_rtl' => false],
            ['code' => 'az', 'name' => 'Azerbaijani', 'sort_order' => 140, 'is_rtl' => false],
            ['code' => 'bm', 'name' => 'Bambara', 'sort_order' => 150, 'is_rtl' => false],
            ['code' => 'ba', 'name' => 'Bashkir', 'sort_order' => 160, 'is_rtl' => false],
            ['code' => 'eu', 'name' => 'Basque', 'sort_order' => 170, 'is_rtl' => false],
            ['code' => 'be', 'name' => 'Belarusian', 'sort_order' => 180, 'is_rtl' => false],
            ['code' => 'bn', 'name' => 'Bengali', 'sort_order' => 190, 'is_rtl' => false],
            ['code' => 'bi', 'name' => 'Bislama', 'sort_order' => 200, 'is_rtl' => false],
            ['code' => 'bs', 'name' => 'Bosnian', 'sort_order' => 210, 'is_rtl' => false],
            ['code' => 'br', 'name' => 'Breton', 'sort_order' => 220, 'is_rtl' => false],
            ['code' => 'bg', 'name' => 'Bulgarian', 'sort_order' => 230, 'is_rtl' => false],
            ['code' => 'my', 'name' => 'Burmese', 'sort_order' => 240, 'is_rtl' => false],
            ['code' => 'ca', 'name' => 'Catalan', 'sort_order' => 250, 'is_rtl' => false],
            ['code' => 'ch', 'name' => 'Chamorro', 'sort_order' => 260, 'is_rtl' => false],
            ['code' => 'ce', 'name' => 'Chechen', 'sort_order' => 270, 'is_rtl' => false],
            ['code' => 'ny', 'name' => 'Chichewa', 'sort_order' => 280, 'is_rtl' => false],
            ['code' => 'zh', 'name' => 'Chinese', 'sort_order' => 290, 'is_rtl' => false],
            ['code' => 'cu', 'name' => 'Church Slavic', 'sort_order' => 300, 'is_rtl' => false],
            ['code' => 'cv', 'name' => 'Chuvash', 'sort_order' => 310, 'is_rtl' => false],
            ['code' => 'kw', 'name' => 'Cornish', 'sort_order' => 320, 'is_rtl' => false],
            ['code' => 'co', 'name' => 'Corsican', 'sort_order' => 330, 'is_rtl' => false],
            ['code' => 'cr', 'name' => 'Cree', 'sort_order' => 340, 'is_rtl' => false],
            ['code' => 'hr', 'name' => 'Croatian', 'sort_order' => 350, 'is_rtl' => false],
            ['code' => 'cs', 'name' => 'Czech', 'sort_order' => 360, 'is_rtl' => false],
            ['code' => 'da', 'name' => 'Danish', 'sort_order' => 370, 'is_rtl' => false],
            ['code' => 'dv', 'name' => 'Divehi', 'sort_order' => 380, 'is_rtl' => true],
            ['code' => 'nl', 'name' => 'Dutch', 'sort_order' => 390, 'is_rtl' => false],
            ['code' => 'dz', 'name' => 'Dzongkha', 'sort_order' => 400, 'is_rtl' => false],
            ['code' => 'en', 'name' => 'English', 'sort_order' => 0, 'is_rtl' => false, 'system' => true],
            ['code' => 'eo', 'name' => 'Esperanto', 'sort_order' => 420, 'is_rtl' => false],
            ['code' => 'et', 'name' => 'Estonian', 'sort_order' => 430, 'is_rtl' => false],
            ['code' => 'ee', 'name' => 'Ewe', 'sort_order' => 440, 'is_rtl' => false],
            ['code' => 'fo', 'name' => 'Faroese', 'sort_order' => 450, 'is_rtl' => false],
            ['code' => 'fj', 'name' => 'Fijian', 'sort_order' => 460, 'is_rtl' => false],
            ['code' => 'fi', 'name' => 'Finnish', 'sort_order' => 470, 'is_rtl' => false],
            ['code' => 'fr', 'name' => 'French', 'sort_order' => 480, 'is_rtl' => true],
            ['code' => 'fr', 'region_code' => 'CA', 'name' => 'French (Canada)', 'sort_order' => 490, 'is_rtl' => false],
            ['code' => 'ff', 'name' => 'Fulah', 'sort_order' => 500, 'is_rtl' => false],
            ['code' => 'gl', 'name' => 'Galician', 'sort_order' => 510, 'is_rtl' => false],
            ['code' => 'lg', 'name' => 'Ganda', 'sort_order' => 520, 'is_rtl' => false],
            ['code' => 'ka', 'name' => 'Georgian', 'sort_order' => 530, 'is_rtl' => false],
            ['code' => 'de', 'name' => 'German', 'sort_order' => 540, 'is_rtl' => false],
            ['code' => 'el', 'name' => 'Greek', 'sort_order' => 550, 'is_rtl' => false],
            ['code' => 'gn', 'name' => 'Guarani', 'sort_order' => 560, 'is_rtl' => false],
            ['code' => 'gu', 'name' => 'Gujarati', 'sort_order' => 570, 'is_rtl' => false],
            ['code' => 'ht', 'name' => 'Haitian', 'sort_order' => 580, 'is_rtl' => false],
            ['code' => 'ha', 'name' => 'Hausa', 'sort_order' => 590, 'is_rtl' => false],
            ['code' => 'he', 'name' => 'Hebrew', 'sort_order' => 600, 'is_rtl' => true],
            ['code' => 'hz', 'name' => 'Herero', 'sort_order' => 610, 'is_rtl' => false],
            ['code' => 'hi', 'name' => 'Hindi', 'sort_order' => 620, 'is_rtl' => false],
            ['code' => 'ho', 'name' => 'Hiri Motu', 'sort_order' => 630, 'is_rtl' => false],
            ['code' => 'hu', 'name' => 'Hungarian', 'sort_order' => 640, 'is_rtl' => false],
            ['code' => 'is', 'name' => 'Icelandic', 'sort_order' => 650, 'is_rtl' => false],
            ['code' => 'io', 'name' => 'Ido', 'sort_order' => 660, 'is_rtl' => false],
            ['code' => 'ig', 'name' => 'Igbo', 'sort_order' => 670, 'is_rtl' => false],
            ['code' => 'id', 'name' => 'Indonesian', 'sort_order' => 680, 'is_rtl' => false],
            ['code' => 'ia', 'name' => 'Interlingua', 'sort_order' => 690, 'is_rtl' => false],
            ['code' => 'ie', 'name' => 'Interlingue', 'sort_order' => 700, 'is_rtl' => false],
            ['code' => 'iu', 'name' => 'Inuktitut', 'sort_order' => 710, 'is_rtl' => false],
            ['code' => 'ik', 'name' => 'Inupiaq', 'sort_order' => 720, 'is_rtl' => false],
            ['code' => 'ga', 'name' => 'Irish', 'sort_order' => 730, 'is_rtl' => false],
            ['code' => 'it', 'name' => 'Italian', 'sort_order' => 740, 'is_rtl' => false],
            ['code' => 'ja', 'name' => 'Japanese', 'sort_order' => 750, 'is_rtl' => false],
            ['code' => 'jv', 'name' => 'Javanese', 'sort_order' => 760, 'is_rtl' => false],
            ['code' => 'kl', 'name' => 'Kalaallisut', 'sort_order' => 770, 'is_rtl' => false],
            ['code' => 'kn', 'name' => 'Kannada', 'sort_order' => 780, 'is_rtl' => false],
            ['code' => 'kr', 'name' => 'Kanuri', 'sort_order' => 790, 'is_rtl' => false],
            ['code' => 'ks', 'name' => 'Kashmiri', 'sort_order' => 800, 'is_rtl' => true],
            ['code' => 'kk', 'name' => 'Kazakh', 'sort_order' => 810, 'is_rtl' => false],
            ['code' => 'km', 'name' => 'Khmer', 'sort_order' => 820, 'is_rtl' => false],
            ['code' => 'ki', 'name' => 'Kikuyu', 'sort_order' => 830, 'is_rtl' => false],
            ['code' => 'rw', 'name' => 'Kinyarwanda', 'sort_order' => 840, 'is_rtl' => false],
            ['code' => 'kv', 'name' => 'Komi', 'sort_order' => 850, 'is_rtl' => false],
            ['code' => 'kg', 'name' => 'Kongo', 'sort_order' => 860, 'is_rtl' => false],
            ['code' => 'ko', 'name' => 'Korean', 'sort_order' => 870, 'is_rtl' => false],
            ['code' => 'kj', 'name' => 'Kuanyama', 'sort_order' => 880, 'is_rtl' => false],
            ['code' => 'ku', 'name' => 'Kurdish', 'sort_order' => 890, 'is_rtl' => false],
            ['code' => 'ky', 'name' => 'Kyrgyz', 'sort_order' => 900, 'is_rtl' => false],
            ['code' => 'lo', 'name' => 'Lao', 'sort_order' => 910, 'is_rtl' => false],
            ['code' => 'la', 'name' => 'Latin', 'sort_order' => 920, 'is_rtl' => false],
            ['code' => 'lv', 'name' => 'Latvian', 'sort_order' => 930, 'is_rtl' => false],
            ['code' => 'li', 'name' => 'Limburgish', 'sort_order' => 940, 'is_rtl' => false],
            ['code' => 'ln', 'name' => 'Lingala', 'sort_order' => 950, 'is_rtl' => false],
            ['code' => 'lt', 'name' => 'Lithuanian', 'sort_order' => 960, 'is_rtl' => false],
            ['code' => 'lu', 'name' => 'Luba-Katanga', 'sort_order' => 970, 'is_rtl' => false],
            ['code' => 'lb', 'name' => 'Luxembourgish', 'sort_order' => 980, 'is_rtl' => false],
            ['code' => 'mk', 'name' => 'Macedonian', 'sort_order' => 990, 'is_rtl' => false],
            ['code' => 'mg', 'name' => 'Malagasy', 'sort_order' => 1000, 'is_rtl' => false],
            ['code' => 'ms', 'name' => 'Malay', 'sort_order' => 1010, 'is_rtl' => false],
            ['code' => 'ml', 'name' => 'Malayalam', 'sort_order' => 1020, 'is_rtl' => false],
            ['code' => 'mt', 'name' => 'Maltese', 'sort_order' => 1030, 'is_rtl' => false],
            ['code' => 'gv', 'name' => 'Manx', 'sort_order' => 1040, 'is_rtl' => false],
            ['code' => 'mi', 'name' => 'Maori', 'sort_order' => 1050, 'is_rtl' => false],
            ['code' => 'mr', 'name' => 'Marathi', 'sort_order' => 1060, 'is_rtl' => false],
            ['code' => 'mh', 'name' => 'Marshallese', 'sort_order' => 1070, 'is_rtl' => false],
            ['code' => 'mn', 'name' => 'Mongolian', 'sort_order' => 1080, 'is_rtl' => false],
            ['code' => 'na', 'name' => 'Nauru', 'sort_order' => 1090, 'is_rtl' => false],
            ['code' => 'nv', 'name' => 'Navajo', 'sort_order' => 1100, 'is_rtl' => false],
            ['code' => 'ng', 'name' => 'Ndonga', 'sort_order' => 1110, 'is_rtl' => false],
            ['code' => 'ne', 'name' => 'Nepali', 'sort_order' => 1120, 'is_rtl' => false],
            ['code' => 'nd', 'name' => 'North Ndebele', 'sort_order' => 1130, 'is_rtl' => false],
            ['code' => 'se', 'name' => 'Northern Sami', 'sort_order' => 1140, 'is_rtl' => false],
            ['code' => 'no', 'name' => 'Norwegian', 'sort_order' => 1150, 'is_rtl' => false],
            ['code' => 'nb', 'name' => 'Norwegian Bokmal', 'sort_order' => 1160, 'is_rtl' => false],
            ['code' => 'nn', 'name' => 'Norwegian Nynorsk', 'sort_order' => 1170, 'is_rtl' => false],
            ['code' => 'oc', 'name' => 'Occitan', 'sort_order' => 1180, 'is_rtl' => false],
            ['code' => 'oj', 'name' => 'Ojibwa', 'sort_order' => 1190, 'is_rtl' => false],
            ['code' => 'or', 'name' => 'Oriya', 'sort_order' => 1200, 'is_rtl' => false],
            ['code' => 'om', 'name' => 'Oromo', 'sort_order' => 1210, 'is_rtl' => false],
            ['code' => 'os', 'name' => 'Ossetian', 'sort_order' => 1220, 'is_rtl' => false],
            ['code' => 'pi', 'name' => 'Pali', 'sort_order' => 1230, 'is_rtl' => false],
            ['code' => 'ps', 'name' => 'Pashto', 'sort_order' => 1240, 'is_rtl' => true],
            ['code' => 'fa', 'name' => 'Persian', 'sort_order' => 1250, 'is_rtl' => true],
            ['code' => 'pl', 'name' => 'Polish', 'sort_order' => 1260, 'is_rtl' => false],
            ['code' => 'pt', 'name' => 'Portuguese', 'sort_order' => 1270, 'is_rtl' => false],
            ['code' => 'pt', 'region_code' => 'BR', 'name' => 'Portuguese (Brazil)', 'sort_order' => 1280, 'is_rtl' => false],
            ['code' => 'pa', 'name' => 'Punjabi', 'sort_order' => 1290, 'is_rtl' => false],
            ['code' => 'qu', 'name' => 'Quechua', 'sort_order' => 1300, 'is_rtl' => false],
            ['code' => 'ro', 'name' => 'Romanian', 'sort_order' => 1310, 'is_rtl' => false],
            ['code' => 'rm', 'name' => 'Romansh', 'sort_order' => 1320, 'is_rtl' => false],
            ['code' => 'rn', 'name' => 'Rundi', 'sort_order' => 1330, 'is_rtl' => false],
            ['code' => 'ru', 'name' => 'Russian', 'sort_order' => 1340, 'is_rtl' => false],
            ['code' => 'sm', 'name' => 'Samoan', 'sort_order' => 1350, 'is_rtl' => false],
            ['code' => 'sg', 'name' => 'Sango', 'sort_order' => 1360, 'is_rtl' => false],
            ['code' => 'sa', 'name' => 'Sanskrit', 'sort_order' => 1370, 'is_rtl' => false],
            ['code' => 'sc', 'name' => 'Sardinian', 'sort_order' => 1380, 'is_rtl' => false],
            ['code' => 'gd', 'name' => 'Scottish Gaelic', 'sort_order' => 1390, 'is_rtl' => false],
            ['code' => 'sr', 'name' => 'Serbian', 'sort_order' => 1400, 'is_rtl' => false],
            ['code' => 'sn', 'name' => 'Shona', 'sort_order' => 1410, 'is_rtl' => false],
            ['code' => 'sd', 'name' => 'Sindhi', 'sort_order' => 1420, 'is_rtl' => true],
            ['code' => 'si', 'name' => 'Sinhala', 'sort_order' => 1430, 'is_rtl' => false],
            ['code' => 'sk', 'name' => 'Slovak', 'sort_order' => 1440, 'is_rtl' => false],
            ['code' => 'sl', 'name' => 'Slovenian', 'sort_order' => 1450, 'is_rtl' => false],
            ['code' => 'so', 'name' => 'Somali', 'sort_order' => 1460, 'is_rtl' => false],
            ['code' => 'nr', 'name' => 'South Ndebele', 'sort_order' => 1470, 'is_rtl' => false],
            ['code' => 'st', 'name' => 'Southern Sotho', 'sort_order' => 1480, 'is_rtl' => false],
            ['code' => 'es', 'name' => 'Spanish', 'sort_order' => 1490, 'is_rtl' => false],
            ['code' => 'su', 'name' => 'Sundanese', 'sort_order' => 1500, 'is_rtl' => false],
            ['code' => 'sw', 'name' => 'Swahili', 'sort_order' => 1510, 'is_rtl' => false],
            ['code' => 'ss', 'name' => 'Swati', 'sort_order' => 1520, 'is_rtl' => false],
            ['code' => 'sv', 'name' => 'Swedish', 'sort_order' => 1530, 'is_rtl' => false],
            ['code' => 'tl', 'name' => 'Tagalog', 'sort_order' => 1540, 'is_rtl' => false],
            ['code' => 'ty', 'name' => 'Tahitian', 'sort_order' => 1550, 'is_rtl' => false],
            ['code' => 'tg', 'name' => 'Tajik', 'sort_order' => 1560, 'is_rtl' => false],
            ['code' => 'ta', 'name' => 'Tamil', 'sort_order' => 1570, 'is_rtl' => false],
            ['code' => 'tt', 'name' => 'Tatar', 'sort_order' => 1580, 'is_rtl' => false],
            ['code' => 'te', 'name' => 'Telugu', 'sort_order' => 1590, 'is_rtl' => false],
            ['code' => 'th', 'name' => 'Thai', 'sort_order' => 1600, 'is_rtl' => false],
            ['code' => 'bo', 'name' => 'Tibetan', 'sort_order' => 1610, 'is_rtl' => false],
            ['code' => 'ti', 'name' => 'Tigrinya', 'sort_order' => 1620, 'is_rtl' => false],
            ['code' => 'to', 'name' => 'Tonga', 'sort_order' => 1630, 'is_rtl' => false],
            ['code' => 'ts', 'name' => 'Tsonga', 'sort_order' => 1640, 'is_rtl' => false],
            ['code' => 'tn', 'name' => 'Tswana', 'sort_order' => 1650, 'is_rtl' => false],
            ['code' => 'tr', 'name' => 'Turkish', 'sort_order' => 1660, 'is_rtl' => false],
            ['code' => 'tk', 'name' => 'Turkmen', 'sort_order' => 1670, 'is_rtl' => false],
            ['code' => 'tw', 'name' => 'Twi', 'sort_order' => 1680, 'is_rtl' => false],
            ['code' => 'uk', 'name' => 'Ukrainian', 'sort_order' => 1690, 'is_rtl' => false],
            ['code' => 'ur', 'name' => 'Urdu', 'sort_order' => 1700, 'is_rtl' => true],
            ['code' => 'ug', 'name' => 'Uyghur', 'sort_order' => 1710, 'is_rtl' => true],
            ['code' => 'uz', 'name' => 'Uzbek', 'sort_order' => 1720, 'is_rtl' => false],
            ['code' => 've', 'name' => 'Venda', 'sort_order' => 1730, 'is_rtl' => false],
            ['code' => 'vi', 'name' => 'Vietnamese', 'sort_order' => 1740, 'is_rtl' => false],
            ['code' => 'vo', 'name' => 'Volapuk', 'sort_order' => 1750, 'is_rtl' => false],
            ['code' => 'wa', 'name' => 'Walloon', 'sort_order' => 1760, 'is_rtl' => false],
            ['code' => 'cy', 'name' => 'Welsh', 'sort_order' => 1770, 'is_rtl' => false],
            ['code' => 'fy', 'name' => 'Western Frisian', 'sort_order' => 1780, 'is_rtl' => false],
            ['code' => 'wo', 'name' => 'Wolof', 'sort_order' => 1790, 'is_rtl' => false],
            ['code' => 'xh', 'name' => 'Xhosa', 'sort_order' => 1800, 'is_rtl' => false],
            ['code' => 'yi', 'name' => 'Yiddish', 'sort_order' => 1810, 'is_rtl' => true],
            ['code' => 'yo', 'name' => 'Yoruba', 'sort_order' => 1820, 'is_rtl' => false],
            ['code' => 'za', 'name' => 'Zhuang', 'sort_order' => 1830, 'is_rtl' => false],
            ['code' => 'zu', 'name' => 'Zulu', 'sort_order' => 1840, 'is_rtl' => false],
        ];
    }
}
